# Generated by Django 6.0.3 on 2026-03-10 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_businesssubscriptionpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='opening_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='branch',
            name='opening_balance_date',
            field=models.DateField(blank=True, help_text='Date when the opening balance was set', null=True),
        ),
    ]
