# Generated by Django 6.0.3 on 2026-03-13 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_branch_opening_balance_branch_opening_balance_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockmove',
            name='dest_business',
        ),
        migrations.RemoveField(
            model_name='stockmove',
            name='source_business',
        ),
        migrations.AddField(
            model_name='stockmove',
            name='dest_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='in_moves', to='api.branch'),
        ),
        migrations.AddField(
            model_name='stockmove',
            name='source_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='out_moves', to='api.branch'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warehouses', to='api.branch'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='business',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='warehouses', to='api.business'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='warehouse',
            unique_together={('business', 'code'), ('business', 'name')},
        ),
    ]
