# Generated by Django 5.2.8 on 2026-03-17 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_purchaseorder_notes_purchasereturn_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='notes',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
